[package]
name = "actix1u-ums"
version = "0.1.0"
authors = ["nuts-n-bits <nuts-n-bits@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
